config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /zh|en|ru/ do
    root "pages#home"

    resources :news
    resources :feedbacks, only: [:new, :create]
    resources :orders, only: [:new, :create]

    get 'about' => 'pages#about'
    get 'sale_petroleum' => 'pages#sale_petroleum'
  end

  scope 'assets', as: 'assets', format: false do
    get '/:asset.:format', to: 'assets#show'
  end

  mount Trestle::Engine => '/admin', as: 'trestle'
end

app/models/coal_grade.rb
class CoalGrade < ApplicationRecord
  has_one_attached :pdf_file
  before_save :remove_attach_file_by_flag

  has_many :coal_grade_items, dependent: :destroy

  validates :name, presence: { message: 'can\'t be empty' }

  def remove_attach_file_by_flag
    pdf_file.purge if delete_file? && pdf_file.attached?
    self.delete_file = false
  end
end

app/models/command.rb
class Command < ApplicationRecord
  has_one_attached :image
  before_save :remove_attach_img_by_flag

  validates :person, presence: { message: 'can\'t be empty' }
  validates :desc, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  private

  def self.items
    where(language: I18n.locale)
  end

  def remove_attach_img_by_flag
    image.purge if delete_file? && image.attached?
    self.base_image_url = '' if delete_file? && !base_image_url.nil?
    self.delete_file = false
  end
end

app/models/config.rb
class Config < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :value, presence: { message: 'can\'t be empty' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'Config cannot be deleted'
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :title, presence: { message: 'can\'t be empty' }
  validates :address, presence: { message: 'can\'t be empty' }
  validates :phone_num, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'Contact cannot be deleted'
  end

  private

  def self.items
    where(language: I18n.locale)
      .as_json(only: [:name, :title, :person, :address, :phone_num])
      .group_by { |e| e['name'] }
  end
end

app/models/cookie_element.rb
class CookieElement < ApplicationRecord
  before_destroy :stop_destroy

  validates :title, presence: { message: 'can\'t be empty' }
  validates :btn, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'NavigationPage cannot be deleted'
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :name, :email, :message, presence: true
end

app/models/footer.rb
class Footer < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :title, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'NavigationPage cannot be deleted'
  end
end

app/models/general.rb
class General < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :text, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'NavigationPage cannot be deleted'
  end

  private

  def self.items
    where(language: I18n.locale)
      .as_json(only: [:name, :text])
      .group_by { |e| e['name'] }
  end
end

app/models/navigation.rb
class Navigation < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :title, presence: { message: 'can\'t be empty' }
  validates :url, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'NavigationPage cannot be deleted'
  end

  private

  def self.items
    where(language: I18n.locale)
      .as_json(only: [:name, :title, :url])
      .group_by { |e| e['name'] }
  end
end

app/models/news.rb
class News < ApplicationRecord
  has_one_attached :image
  before_save :remove_attach_img_by_flag

  validates :title, presence: { message: 'can\'t be empty' }
  validates :content, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  private

  def self.items
    where(language: I18n.locale).order(created_at: :desc).limit(3)
  end

  def self.items_by_locale
    where(language: I18n.locale).order(created_at: :desc)
  end

  def remove_attach_img_by_flag
    image.purge if delete_file? && image.attached?
    self.delete_file = false
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :coal_name, :basis_supply, :delivery_direction, :destination_station,
            :name, :email, :message, :count, :organization, :price, :phone,
            presence: true
end

app/models/slider.rb
class Slider < ApplicationRecord
  has_one_attached :image
  before_save :remove_attach_img_by_flag

  validates :text, presence: { message: 'can\'t be empty' }
  # validates :image, presence: { message: 'can\'t be empty' }
  # validates logo_validation

  private

  def self.items
    where(language: I18n.locale)
  end

  def remove_attach_img_by_flag
    image.purge if delete_file? && image.attached?
    self.base_image_url = '' if delete_file? && !base_image_url.nil?
    self.delete_file = false
  end

  def logo_validation
    if image.attached?
      if image.blob.byte_size > 1000000
        image.purge
        self.errors.add(:image, 'Too big')
      elsif !image.blob.content_type.starts_with?('image/')
        image.purge
        self.errors.add(:image, 'Wrong format')
      end
    end
  end
end

app/models/slider_sale.rb
class SliderSale < ApplicationRecord
  has_one_attached :image
  before_save :remove_attach_img_by_flag

  validates :text, presence: { message: 'can\'t be empty' }
  # validates :image, presence: { message: 'can\'t be empty' }

  private

  def self.items
    where(language: I18n.locale)
  end

  def remove_attach_img_by_flag
    image.purge if delete_file? && image.attached?
    self.base_image_url = '' if delete_file? && !base_image_url.nil?
    self.delete_file = false
  end
end

app/models/supply_basis.rb
class SupplyBasis < ApplicationRecord
  before_destroy :stop_destroy

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'SupplyBasis cannot be deleted'
  end
end

app/models/title.rb
class Title < ApplicationRecord
  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :title, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'Title cannot be deleted'
  end
end

app/models/txt_button.rb
class TxtButton < ApplicationRecord
  # extend Mobility
  # translates :title, type: :string

  before_destroy :stop_destroy

  validates :name, presence: { message: 'can\'t be empty' }
  validates :title, presence: { message: 'can\'t be empty' }
  validates :language, presence: { message: 'should be selected' }

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'TxtButton cannot be deleted'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable

  before_destroy :stop_destroy

  def stop_destroy
    raise ActiveRecord::RecordNotDestroyed, 'User cannot be deleted'
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/news_admin/_image_field.html.erb
<style>
    input[type="checkbox"] {
        position: absolute;
        opacity: 0;
    }

    /* Создание стилей для кастомного чекбокса (крестика) */
    .custom-checkbox {
        position: relative;
        display: inline-block;
        width: 20px;
        height: 20px;
        cursor: pointer;
        float: right;
    }

    /* Оформление крестика (левая галочка) */
    .custom-checkbox::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        width: 10px;
        height: 2px;
        background-color: black;
        transform: translate(-50%, -50%) rotate(-45deg);
    }

    /* Оформление крестика (правая галочка) */
    .custom-checkbox::after {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        width: 10px;
        height: 2px;
        background-color: black;
        transform: translate(-50%, -50%) rotate(45deg);
    }

    .preview-image {
        max-width: 100%;
        height: auto;
        float: right;
        display: none;
    }
</style>
<script>
    function previewImg(input) {
        show_hide_block(false);
        let preview = document.querySelector('.preview-image');
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                preview.src = e.target.result;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    function deleteImg(checkbox) {
        show_hide_block(checkbox.checked);
    }

    function show_hide_block(status) {
        let image_preview = document.querySelector('.preview-image');
        let hiddenFieldValue = document.getElementById('hidden-field-id');
        let checkbox = document.getElementById('remove_image');
        let checkbox_label = document.getElementById('remove_image_label');
        if (status) {
            image_preview[0].style.display = 'none';
            checkbox.style.display = 'none';
            checkbox_label.style.display = 'none';
            hiddenFieldValue.value = true;
        } else {
            image_preview[0].style.display = 'block';
            checkbox.style.display = 'block';
            checkbox.checked = false;
            checkbox_label.style.display = 'block';
            hiddenFieldValue.value = false;
        }
    }
</script>

<div class="container">
  <div class="raw ml-2">
    <input type="checkbox" id="remove_image" onchange="deleteImg(this)">
    <label for="remove_image" class="custom-checkbox" id="remove_image_label"></label>
  </div>
  <div class="raw mb-5 ml-0 mt-2">
    <label>
      <b>Image</b>
    </label>
    <%= file_field :news, :image, class: 'image-upload-field', onchange: "previewImg(this);" %>
    <% if news.image.attached? %>
      <%= image_tag main_app.rails_blob_path(news.image), class: 'preview-image' %>
    <% else %>
      <%= image_tag '/assets/icons/close.svg', class: 'preview-image' %>
    <% end %>
    <%= hidden_field :news, :delete_file, value: 'false', id: 'hidden-field-id' %>
    <%#= hidden_field :authenticity_token, value: form_authenticity_token %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-hero">
  <video class="home-hero__background" autoplay="true" muted="muted" loop="true" playsinline="playsinline">
    <source src="/assets/video/hero.mp4" type="video/mp4"/>
    <source src="/assets/video/hero.webm" type="video/webm"/>
  </video>

  <div class="container">
    <div class="home-hero__left">
      <h1>
        <%= @titles['slogan'][0]['title'] %>
      </h1>
      <a class="button button_primary popup-open" href="#popup-order">
        <%= @buttons['order'][0]['title'] %>
      </a>
    </div>
    <div class="home-hero__right">
      <div class="home-hero-counter">
        <div class="home-hero-counter__text"><%= @titles['coal_supplied'][0]['title'] %></div>
        <div class="home-hero-counter__main">
          <span class="home-hero-counter__value" data-counter='<%= @coal_count %>' data-speed="500">0</span>
          <span class="home-hero-counter_small">&nbsp;<%= @titles['coal_count_el'][0]['title'] %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="home-hero__scroll"><img src="/assets/icons/angle-down.svg" alt=""/></div>
</div>

<div class="home-about home-section" id="about">
  <div class="home-about-head">
    <div class="container">
      <div class="home-about-head__title">SIBSTAR GROUP</div>
      <h2 class="home-about-head__h2"><%= @titles['about_company'][0]['title'] %></h2>
    </div>
  </div>
  <div class="container">
    <div class="home-about-slider swiper" id="home-about-slider" data-speed="<%= @timer %>">
      <div class="swiper-wrapper">
        <% @slides.each do |slide| %>
          <div class="swiper-slide home-about-slider__slide">
            <div class="home-about-slider__content">
              <div class="home-about-slider__text">
                <%= slide['text'].html_safe %>
              </div>
            </div>
            <div class="home-about-slider__image">
              <% if slide.image.attached? %>
                <img src="<%= url_for(slide.image) %>" alt="" style="height: 360px;-o-object-fit: cover;object-fit: cover;">
              <% else %>
                <img src="<%= slide['base_image_url'] %>" alt="" style="height: 360px;-o-object-fit: cover;object-fit: cover;"/>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="home-about-slider-navigation">
        <div class="home-about-slider-navigation__item"></div>
      </div>
    </div>
    <div class="home-about__command">
      <a class="button button_outline popup-open" href="#popup-command">
        <%= @buttons['command'][0]['title'] %>
      </a>
    </div>
  </div>
</div>
<div class="home-coal-sales home-section" id="coal-sales">
  <div class="container">
    <h2 class="home-coal-sales__h2"><%= @titles['coal_sales'][0]['title'] %></h2>
    <p class="home-coal-sales__start-text">
      <%= @general['coal_desc'][0]['text'].html_safe %>
    </p>
    <% @coal_grades.each do |grade| %>
      <%= render 'shared/home_coal_sales_accordion/info', grade: grade %>
    <% end %>
  </div>
</div>
<div class="home-supply-basis home-section" id="supply-basis">
  <div class="container">
    <h2 class="home-supply-basis__h2"><%= @titles['supply_basic'][0]['title'] %></h2>
    <div class="home-supply-basis__buttons">
      <button class="button button_outline" data-path="dap" data-cities="mihajlo-semenovoskaya,grodekovo,kamyshovaya">DAP</button>
      <button class="button button_outline" data-path="fob" data-cities="blagoveshensk,habarovsk">FOB</button>
      <button class="button button_outline" data-path="cfr" data-cities="habarovsk">CFR</button>
      <button class="button home-supply-basis__button-close"><img src="/assets/icons/close.svg" alt=""/></button>
    </div>
  </div>
  <div class="home-supply-basis-map">
    <div class="home-supply-basis-map__background">
      <img src="/assets/supply-basis-map.jpg" alt="" srcset="/assets/supply-basis-map.jpg 1x, assets/supply-basis-map@2x.jpg 2x, assets/supply-basis-map@3x.jpg 3x"/>
    </div>
    <div class="home-supply-basis-map__path home-supply-basis-map__path_default">
      <img src="/assets/supply-basis-path-default.svg" alt=""/></div>
    <div class="home-supply-basis-map__path home-supply-basis-map__path_dap">
      <img src="/assets/supply-basis-path-dap.svg" alt=""/></div>
    <div class="home-supply-basis-map__path home-supply-basis-map__path_fob">
      <img src="/assets/supply-basis-path-fob.svg" alt=""/></div>
    <div class="home-supply-basis-map__path home-supply-basis-map__path_cfr">
      <img src="/assets/supply-basis-path-cfr.svg" alt=""/></div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_kuzbas" data-city="kuzbas">
      <div class="home-supply-basis-map-item__dot"></div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['kuzbass'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_hakassia" data-city="hakassia">
      <div class="home-supply-basis-map-item__dot"></div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['khakasia'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_small home-supply-basis-map-item_blagoveshensk" data-city="blagoveshensk">
      <div class="home-supply-basis-map-item__dot">
        <div class="home-supply-basis-map-item__plus"></div>
      </div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['blagoveshchensk'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_small home-supply-basis-map-item_habarovsk" data-city="habarovsk">
      <div class="home-supply-basis-map-item__dot">
        <div class="home-supply-basis-map-item__plus"></div>
      </div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['khabarovsk'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_small home-supply-basis-map-item_mihajlo-semenovoskaya" data-city="mihajlo-semenovoskaya">
      <div class="home-supply-basis-map-item__dot">
        <div class="home-supply-basis-map-item__plus"></div>
      </div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['semenovskaya'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_small home-supply-basis-map-item_grodekovo" data-city="grodekovo">
      <div class="home-supply-basis-map-item__dot">
        <div class="home-supply-basis-map-item__plus"></div>
      </div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['grodekovo'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-item home-supply-basis-map-item_small home-supply-basis-map-item_kamyshovaya" data-city="kamyshovaya">
      <div class="home-supply-basis-map-item__dot">
        <div class="home-supply-basis-map-item__plus"></div>
      </div>
      <div class="home-supply-basis-map-item__name"><%= @supply_basis['kamyshovaya'][0]['title'] %></div>
    </div>
    <div class="home-supply-basis-map-popup home-supply-basis-map-popup_blagoveshensk">
      <div class="home-supply-basis-map-popup__close"><img src="/assets/icons/close.svg" alt=""/></div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @supply_basis['river_port'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__title"><%= @supply_basis['blagoveshchensk'][0]['title'] %></div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @titles['supply_basic'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__link" data-path="fob">FOB</div>
        <div class="home-supply-basis-map-popup__city">Хэйхе</div>
      </div>
    </div>
    <div class="home-supply-basis-map-popup home-supply-basis-map-popup_habarovsk">
      <div class="home-supply-basis-map-popup__close"><img src="/assets/icons/close.svg" alt=""/></div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @supply_basis['river_port'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__title"><%= @supply_basis['khabarovsk'][0]['title'] %></div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @titles['supply_basic'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__link" data-path="fob">FOB</div>
        <div class="home-supply-basis-map-popup__city">Тунцзян</div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__link" data-path="cfr">СFR</div>
        <div class="home-supply-basis-map-popup__city">Фуюань</div>
        <div class="home-supply-basis-map-popup__city">Тунцзян</div>
      </div>
    </div>
    <div class="home-supply-basis-map-popup home-supply-basis-map-popup_mihajlo-semenovoskaya">
      <div class="home-supply-basis-map-popup__close"><img src="/assets/icons/close.svg" alt=""/></div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @supply_basis['river_port'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__title"><%= @supply_basis['semenovskaya'][0]['title'] %></div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @titles['supply_basic'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__link" data-path="dap">DAP</div>
        <div class="home-supply-basis-map-popup__city">Тунцзян</div>
      </div>
    </div>
    <div class="home-supply-basis-map-popup home-supply-basis-map-popup_grodekovo">
      <div class="home-supply-basis-map-popup__close"><img src="/assets/icons/close.svg" alt=""/></div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @supply_basis['river_port'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__title"><%= @supply_basis['grodekovo'][0]['title'] %></div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @titles['supply_basic'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__link" data-path="dap">DAP</div>
        <div class="home-supply-basis-map-popup__city">Суйфэнхэ</div>
      </div>
    </div>
    <div class="home-supply-basis-map-popup home-supply-basis-map-popup_kamyshovaya">
      <div class="home-supply-basis-map-popup__close"><img src="/assets/icons/close.svg" alt=""/></div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @supply_basis['river_port'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__title"><%= @supply_basis['kamyshovaya'][0]['title'] %></div>
      </div>
      <div class="home-supply-basis-map-popup__item">
        <div class="home-supply-basis-map-popup__type"><%= @titles['supply_basic'][0]['title'] %></div>
        <div class="home-supply-basis-map-popup__link" data-path="dap">DAP</div>
        <div class="home-supply-basis-map-popup__city">Хунчунь</div>
      </div>
    </div>
    <%= render 'shared/video/dap' %>
    <%= render 'shared/video/fob' %>
    <%= render 'shared/video/cfr' %>
  </div>
</div>
<div class="home-news home-section" id="news">
  <div class="container">
    <h2 class="home-news__h2"><%= @titles['news'][0]['title'] %></h2>
    <div class="news-list">
      <% @news.each do |news| %>
        <a class="news-list-item" href="<%= news_path(id: news.id) %>">
          <span class="news-list-item__date"><%= news.created_at.strftime('%d-%m-%Y') %></span>
          <span class="news-list-item__title"><%= news.title %></span>
          <span class="news-list-item__more">
            <%= @buttons['read'][0]['title'] %>
            <span class="news-list-item__more_arrow">→</span>
          </span>
        </a>
      <% end %>
    </div>
    <div class="home-news__button">
      <a class="button button_outline button_invert" href="/news?<%= request.original_url.split('?').last %>">
        <%= @buttons['news'][0]['title'] %>
      </a>
    </div>
  </div>
</div>
<%= render 'shared/navigation_page' %>

app/views/shared/_navigation.html.erb
<div class="navigation">
  <div class="container">
    <div class="navigation__left">
      <div class="navigation-contact">
        <div class="navigation-contact__title">
          <%= @contacts['cooperation'][0]['title'] %>
        </div>
        <a class="navigation-contact__item" href="tel:<%= @contacts['cooperation'][0]['phone_num'] %>">
          <%= @contacts['cooperation'][0]['phone_num'] %>
        </a>
        <a class="navigation-contact__item navigation-contact__item_underline" href="<%= @contacts['cooperation'][0]['address'] %>">
          <%= @contacts['cooperation'][0]['address'] %>
        </a>
      </div>
      <div class="navigation-contact">
        <div class="navigation-contact__title">
          <%= @contacts['gq'][0]['title'] %>
        </div>
        <a class="navigation-contact__item" href="tel:<%= @contacts['gq'][0]['phone_num'] %>">
          <%= @contacts['gq'][0]['phone_num'] %>
        </a>
        <a class="navigation-contact__item navigation-contact__item_underline" href="mailto:<%= @contacts['gq'][0]['address'] %>">
          <%= @contacts['gq'][0]['address'] %>
        </a>
      </div>
    </div>
    <nav class="navigation__right">
      <ul>
        <li class="navigation__li">
          <% if @navigation['about'][0]['url'].blank? %>
            <a class="navigation__link navigation__link_disabled">
              <div class="navigation__link_text">
                <%= @navigation['about'][0]['title'] %>
              </div>
              <div class="navigation__link_soon">
                <%= @navigation['soon'][0]['title'] %>
              </div>
            </a>
          <% else %>
            <%= link_to "#{@navigation['about'][0]['title']}", about_path(:locale => "#{I18n.locale}"), class: "navigation__link" %>
          <% end %>
        </li>
        <li class="navigation__li">
          <% if @navigation['sale_petroleum'][0]['url'].blank? %>
            <a class="navigation__link navigation__link_disabled">
              <div class="navigation__link_text">
                <%= @navigation['sale_petroleum'][0]['title'] %>
              </div>
              <div class="navigation__link_soon">
                <%= @navigation['soon'][0]['title'] %>
              </div>
            </a>
          <% else %>
            <%= link_to "#{@navigation['sale_petroleum'][0]['title']}", sale_petroleum_path(:locale => "#{I18n.locale}"), class: "navigation__link" %>
          <% end %>
        </li>
        <li class="navigation__li">
          <% if @navigation['agricultural'][0]['url'].blank? %>
            <a class="navigation__link navigation__link_disabled">
              <div class="navigation__link_text">
                <%= @navigation['agricultural'][0]['title'] %>
              </div>
              <div class="navigation__link_soon">
                <%= @navigation['soon'][0]['title'] %>
              </div>
            </a>
          <% else %>
            <a class="navigation__link" href="<%= @navigation['agricultural'][0]['url'] %>">
              <%= @navigation['agricultural'][0]['title'] %>
            </a>
          <% end %>
        </li>
        <li class="navigation__li">
          <% if @navigation['coal_online'][0]['url'].blank? %>
            <a class="navigation__link navigation__link_disabled">
              <div class="navigation__link_text">
                <%= @navigation['coal_online'][0]['title'] %>
              </div>
              <div class="navigation__link_soon">
                <%= @navigation['soon'][0]['title'] %>
              </div>
            </a>
          <% else %>
            <a class="navigation__link" href="<%= @navigation['coal_online'][0]['url'] %>">
              <%= @navigation['coal_online'][0]['title'] %>
            </a>
          <% end %>
        </li>
        <li class="navigation__li">
          <a class="navigation__link" href="#contact">
            <%= @navigation['contact'][0]['title'] %>
          </a>
        </li>
        <li class="navigation__li">
          <a class="navigation__link" href="/news?<%= request.original_url.split('?').last %>">
            <%= @navigation['news'][0]['title'] %>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>